######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 29 11:19:45 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
