######################################################################
# Automatically generated by qmake (3.0) Mon Jun 29 11:31:44 2015
######################################################################

TEMPLATE = app
TARGET = viewer_test
INCLUDEPATH += .

# Input
SOURCES += main.cpp
